[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
bonding_curve = "11111111111111111111111111111111"

[programs.devnet]
bonding_curve = "11111111111111111111111111111111"

[programs.mainnet]
bonding_curve = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/filthy/.config/solana/id.json"
endpoint = "https://devnet.helius-rpc.com/?api-key=0db9012d-9281-4251-a54f-c780e58fc3d7"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
