[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = true

[programs.localnet]
bonding_curve = "11111111111111111111111111111111"

[programs.devnet]
bonding_curve = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypair.json"
endpoint = "https://devnet.helius-rpc.com/?api-key=YOUR_HELIUS_RPC_API_KEY"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metadata.so"

[[test.genesis]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"
program = "tests/fixtures/token.so"

[workspace]
members = ["programs/bonding-curve"]

[programs.mainnet]
bonding_curve = "11111111111111111111111111111111"

[test.validator]
url = "https://api.devnet.solana.com"
startup_wait = 90

[[test.validator.clone]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"